import './globals.css'
import { Inter } from 'next/font/google'
import { ApolloWrapper } from "@/libs/apolloWrapper";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Staff Mapping',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}><ApolloWrapper>{children}</ApolloWrapper></body>
    </html>
  )
}
